### PR TITLE
feat(Liquid): Add liquid textures!

### PR DESCRIPTION
**Pull request by xMikux**
Thanks @RenanMsV for this liquid contribute.

---
Ref https://github.com/RenanMsV/slimefun-liquid-resource-pack/issues/1

### CODE REVIEW

**Comment by xMikux** [comment]
@all-contributors add @RenanMsV as design

**Comment by RenanMsV** [comment]
I really appreciate it. Good job on the resource pack.

**Comment by xMikux** [comment]
@RenanMsV a small question, Does molten ore have texture? or apply same material?

image
image
(you can also take a look if it correct)

**Comment by RenanMsV** [comment]
image
image
image
Both Mixer and Liquids group have their textures. The Ore such as diamond ore uses the same texture as a normal diamond. Thats how mine looks like.

**Comment by xMikux** [comment]
oka, I have update it, molten ore should use the same material.
also, I commented on some unused model id to ensure they won't mix with other textures.

**Pull request merged**
