### PR TITLE
[Chore] Update names to match the slimefun id

### PR DESCRIPTION
**Pull request by JustAHuman-xD**
## Description
See #29 

## Changes
- (in theory) renames any files that have a non matching name, ie. “basic_board” -> “basic_circuit_board”
- (in theory) renames any references that have a non matching name (same idea as above)
- The changes that git shows aren’t quite accurate, it guesses a lot and is wrong sometimes so it might show a file being essentially turned into a completely separate file, but the original file still exists it’s just git being weird.

## Testing
I haven’t tested anything yet, this was done via a [script](https://github.com/JustAHuman-xD/RandomCodingStuff/blob/main/resourcepack%20remapper/easy_rename.py) (idk if I pushed the latest version of it yet, I can’t remember and I’m making this on my phone lol) and as you can see for some reason the number of additions is much lower then the number of deletions, I’m not sure why yet and want to figure that out before we merge anything.

### CODE REVIEW

**Comment by xMikux** [comment]
image
Look like there are some missing, I will fix it directly.

**Comment by xMikux** [comment]
I will merge it first.
Can you help me test if all things are correct? (include your SlimefunEssentials)
You can dm me on Discord, this much quickly for testing. Thanks!

**Comment by JustAHuman-xD** [comment]
Nice!

**Comment by JustAHuman-xD** [comment]
> I will merge it first.
> 
> Can you help me test if all things are correct? (include your SlimefunEssentials)
> 
> You can dm me on Discord, this much quickly for testing. Thanks!

What's your discord?

**Comment by xMikux** [comment]
> > I will merge it first.
> > Can you help me test if all things are correct? (include your SlimefunEssentials)
> > You can dm me on Discord, this much quickly for testing. Thanks!
> 
> What's your discord?

.efina

**Review by xMikux — APPROVED** [review]

**Pull request merged**
